### ISSUE TITLE
shinyDeviceAPI, access GPS/accelerometer data on mobile devices in shiny apps

### ISSUE THREAD

**Issue by haozhu233** [ropensci/unconf17#29]
Mobile devices have unique input sources like GPS, acceleration, device orientation, camera and even video streaming. A Good news is that developers can access these info through APIs in javascript. Right now if I want to use these inputs in a shiny app, it seems that I will have to write some javascript in ui.R. It would be nice if programmers can access these info more easily in R. 

Also, since we do our programming on desktops, which usually don't have GPS or accelerometer, it would be nice to be able to simulate data while users do their shiny programming. There can be a global option controlling it. 

I found the following materials might be helpful:
https://github.com/AugustT/shiny_geolocation
https://github.com/trestletech/shinyStore
[Exploring the JavaScript Device APIs](http://blog.teamtreehouse.com/exploring-javascript-device-apis)

**Comment by carlganz** [comment]
Someone did this: https://github.com/nstrayer/shinysense

**Comment by haozhu233** [comment]
that's pretty cool!
