### ISSUE TITLE
Planning + discussing a package's development

### ISSUE THREAD

**Issue by sfirke** [ropensci/unconf17#57]
It was brought up in #47 that people making future requests or wanting to contribute might not know what's in scope for a package or planned for the future (and what's a high or low priority).

Where/how do you plan or talk about what is next for a package?  I find single GitHub issues to be too narrow and a set of GitHub issues to be too fragmented for these conversations.  I'd like some open way to show people the big picture (and specific plans) for what I'm thinking for short, medium-, and long-term direction and features.  Then others could chime in.  I could use it to prioritize my own development time, point people to it who want to make a contribution, and direct others there re: feature requests so they can see what I'm thinking (and thus how something might be in or out of scope).

**Comment by sckott** [comment]
@sfirke Do you ever use milestones?  I group my issues in milestones, and often point people to a milestone so they can see what's planned for each CRAN push. However, this doesn't deal with what's in and out of scope

**Comment by MilesMcBain** [comment]
I was stalking @krlmlr's [taskboard for Tibble](https://github.com/tidyverse/tibble/projects/1) recently and it was pretty informative.

**Comment by stephlocke** [comment]
+1 on milestones and projects

I especially like the projects boards as I'm used to working kanban style

**Comment by sfirke** [comment]
I have never used milestones or projects/taskboards, both look useful - thanks for the recs!  These look good for managing and displaying upcoming features.  Does anyone have a place to have big discussions about the soul or major direction of a package?

**Comment by sckott** [comment]
Discussion forums could work. If its an ropensci pkg, then https://discuss.ropensci.org/

**Comment by stephlocke** [comment]
@sfirke I'm currently using question tagged github issues as the means for soliciting discussion and I guess these unconf issues are the embodiment of using github to have big discussions about the major directions of a package :D 

FWIW it has advantages of keeping everything local to the project, doesn't get lost like slack messages, and doesn't add any extra burden to you as the project owner

**Comment by sfirke** [comment]
Milestones, taskboards, projects, issues: this one is covered IMO.
