### ISSUE TITLE
Praise in multiple languages

### ISSUE THREAD

**Issue by gaborcsardi** [ropensci/unconf17#62]
A fun project, that only takes a minute to contribute to.

This is https://github.com/rladies/praise:
```r
for (i in 1:5) print(praise::praise())
#> [1] "You are priceless!"
#> [1] "You are fantabulous!"
#> [1] "You are gnarly!"
#> [1] "You are doozie!"
#> [1] "You are supreme!"
```
It can also be a bit more sophisticated:
```r
praise::praise("${Exclamation}! ${EXCLAMATION}!-${EXCLAMATION}! This is just ${adjective}!")
#> [1] "Ah! AWW!-WEE! This is just perfect!"
```

Ideas for praise improvements:
* Adding nice words to the list(s), or removing an inappropriate ones (they slip in, sometimes). This is the simplest possible pull request, so it is ideal for a first PR.
* International praise, this is already possible in the dev version of the package. All languages are welcome! More here: https://github.com/rladies/praise/blob/international/inst/international.md
* Adding (more) emoticons? Here is a nice collection of them: https://github.com/wooorm/emoticon/blob/master/index.json
* Can we support emojis? (Might be hard to detect emoji support, but the user can turn them on manually...)
* Auto-translation for not (yet) supported languages, using some API, if there is one available.
* Adding other parts of speech, e.g. metaphors: `You code is wonderland.`, or others.
* etc ?

**Comment by karthik** [comment]
Tagging @leeper and @richierocks in case there are tie ins with their Rconsortium grant.
