### ISSUE TITLE
#rstats community

### ISSUE THREAD

**Issue by ShanEllis** [ropensci/unconf17#63]
While maybe not exactly a _project_, something I'd love to chat more with people at the unconf about is how to make sure the #rstats community is looking ahead and including both concepts that and individuals who may not otherwise be on the community's radar.  For example:
1. ensuring that we're not missing tools/ideas/concepts that exist in related communities due to any possible tunnel vision from interacting primarily with R-people? (I am _totally_ guilty of this, so I want to know what else is out there! What am I missing? What should I be doing to be more well-rounded?)
2. Keeping up with the community on twitter is a lot of fun and there are a lot of rockstars who are super active..which makes this community SO awesome...but are we missing people who may not be on twitter? Is there a better way to include newcomers in conversations? What can I do to help (even though I'm a ~newcomer myself)?

**Comment by stefaniebutland** [comment]
As rOpenSci's Community Manager, I 100% support this and appreciate @ShanEllis for adding it as an issue.

For those who might be sheepish about stating their opinions here for all to see, would great if people just identified themselves here as being interested in talking / listening about this. Good way for us to look for each other at unconf!

**Comment by sckott** [comment]
Great idea @ShanEllis !

**Comment by jules32** [comment]
I'm definitely interested!

**Comment by stefaniebutland** [comment]
@jules32 I was going to ping you about this to channel the community manager in you! Glad you beat me to it

**Comment by eringrand** [comment]
I am also interested in chatting about this. :)

**Comment by karthik** [comment]
Count me in.

**Comment by bzkrouse** [comment]
Great idea! I'm interested too! :)

**Comment by njtierney** [comment]
Sounds great, count me in as well! :)

**Comment by ateucher** [comment]
I'm definitely in - I'm continuously trying to foster an engaged R community where I work (in government), and it is challenging.

**Comment by Ironholds** [comment]
+10000

**Comment by jenniferthompson** [comment]
Definitely interested!

**Comment by nistara** [comment]
I'm interested as well!

**Comment by jhollist** [comment]
Also interested in this.  Since I'll be remote, ping me on slack or twitter if the conversation gets going.  I'm involved with pushing R at EPA and any ideas to help with that (and to keep us tied into the larger community) will be most welcome!

**Comment by revodavid** [comment]
I'd love to be part of this discussion.

**Comment by stefaniebutland** [comment]
For the record, @ShanEllis wrote up the unconf17 discussion for the rOpenSci blog: https://ropensci.org/blog/blog/2017/06/23/community
