### ISSUE TITLE
Interview Series: Demystifying the Creative/Development Process of the R Community

### ISSUE THREAD

**Issue by kellobri** [ropensci/unconf17#64]
# Would this be cool? (Side Project)
I'm interested in perhaps conducting a series of interviews which could then be turned into a series of rOpenSci blogs. I love listening to podcasts where people are interviewed about their creative/working/training process. I've never interviewed people before, so it might all go terribly wrong, but I'm hoping this could be a cool experiment to attempt during the unconference.

Thanks to @stefaniebutland for the encouragement and for suggesting that @jennybc might be interested?? 

## Please let me know...
- If you think this is a cool idea and you would like to nominate yourself or someone else to be interviewed
- If you like, hate, or have any other suggestions for interview question ideas

## Interview Question Ideas

Basic Stats:
- Name
- Current preferred job title 
- Number of years working in R
- % of your work week spent using R

If you have a “typical” work day:
- Where do you do most of your work? (home, office, coffee shop…)
- What does the first half hour of your typical work day look like?
- What does the last half hour of your typical work day look like ?
- For how long have you maintained this type of work day?
- How much time do you devote toward personal projects?

Which parts of your workflow are standard across most projects, which parts tend to change:
- When you’re planning out a new project, do you have a standard process?
- Do you have a standard process for finishing up a project or transitioning it into maintenance mode?
- If you have any projects in “maintenance mode”, how would you define the work and level of effort there? 
- If you’ve ever had a failed/abandoned project, do you have a process for putting it to bed?
- Do you celebrate after completing a big project? How?
 
Bonus Questions:
- If it were a regular Monday, what three things would make your day great (work related or not)
- Has your interest in r changed over time, how/what ways?
- Is there an awesome book (R related or not) that you think more people should read?

**Comment by karthik** [comment]
I'd love to be part of this!

**Comment by karthik** [comment]
Reminds me a bit of [usethis](https://usesthis.com/interviews/jamie.sanchez/) style posts, but somewhat different in focus.

**Comment by stefaniebutland** [comment]
Thank you for posting this @kellobri! Great example questions. 
Glad you chimed in @karthik! Perhaps you could also take a couple of interviewer-interviewee pics for posts.

@jennybc I told @kellobri about how much you loved talking to @jimhester about his git workflow and the idea of rOpenSci hosting some "how I work" posts. 

Here are some other example posts I collected fyi
**Examples:** 
* This [R Views interview with JJ Allaire ](https://www.rstudio.com/rviews/2016/10/12/interview-with-j-j-allaire/) was popular
* [Lifehacker How We Work](http://lifehacker.com/tag/how-we-work)
  * "Every week, we share the shortcuts, workspaces, and productivity tips of our favorite experts and personalities."
* [101 questions with a bioinformatician](http://www.acgt.me/blog/2016/3/3/101-questions-with-a-bioinformatician-38-gene-myers)
  * Bio of subject followed by brief answers to same set of 5 questions
* [My Digital Toolbox](http://www.nature.com/news/my-digital-toolbox-ecologist-christie-bahlai-talks-data-hygiene-1.15896)
  * A new section of Nature examines the software and websites that make research easier

**Comment by njtierney** [comment]
Wonderful idea, I'd also love to be a part of this!

**Comment by ShanEllis** [comment]
An additional "Bonus Question"  suggestion (I like all of what you have above!). Would need to be refined but something along the lines of: 
Your biggest "duh" moment? (i.e. learning something that made your life _way_ easier...that you probably should have known earlier, realizing a mistake you had been making for way too long, etc.)
....and how did you come to that duh moment? (i.e. looking at someone else's code, twitter, chatting with someone at a conference, etc.)

**Comment by bzkrouse** [comment]
This sounds awesome!! In reading it, I was reminded of this [blog](https://mymorningroutine.com/) about routines.  While not exactly related to working styles, it is fun and relatable to learn what gets people going each day :)

**Comment by noamross** [comment]
Would be happy to be part of this. I think one potential set of questions is to ask how people work _on a team_: How do you collaborate with others? What tools do you use for collaboration and communication? How do you deal with different levels of knowledge and different workflows? How do you learn from each other?

**Comment by Ironholds** [comment]
I would goshdarn love this. Happy to be interviewer, interviewee, transcriber, whatever

**Comment by stefaniebutland** [comment]
> how people work on a team: How do you collaborate with others? What tools do you use for collaboration and communication? How do you deal with different levels of knowledge and different workflows? How do you learn from each other?

Would make a great blog post about how people did this at the unconf, if someone was interested in this topic.

**Comment by nistara** [comment]
This is a great idea! I just spoke with @stefaniebutland about recording video during the unconf, and she mentioned this side project and the possibility of getting videos of the interviews as well to edit and put together. Would anyone be open to it? 
Look forward to meeting everyone :)

**Comment by jules32** [comment]
Hi @kellobri, 

I love this idea!! Listening to people's stories and getting a sense of the friendly people behind the code has been huge for me as I've been becoming a data scientist. 

If you're interested, I'd be happy to be interviewed too. I was pretty intimidated when I started learning to code but I overcame that and we've built a whole ocean program with these tools and are teaching other environmental scientists all over the world :)

**Comment by stefaniebutland** [comment]
@kellobri I wonder if there is value in pairing some people up as interviewers and interviewees before the unconf in order to save some face-to-face time. Truly wondering, not being passive aggressive 😉 . Some people might be dying to talk with/interview a specific person so they could declare it here and the group might decide on a set of questions that interviewers could use or a limited pool they could select from. (Of course, also good/important to have this open to others to join in at unconf)

@kellobri You're under no obligation to take this on to organize (you might also want to write some code, or not) but you get first dibs since it was your initiative. I'm happy to help in any way. I'd love to post interviews on the rOpenSci blog every 2 months x 6 for example and tweet about them to our nearly 13,000 followers!

In thinking about interviewees, beyond just the perceived experts, in our community there is a heap of value in highlighting and implicitly promoting diversity of all types - sectors of work like gov't, industry, academia, non-profit; different genders, underrepresented minorities, people who quietly produce awesome things without drawing attention to themselves, people who act as reviewers for software onboarding, ...

btw, I love this interview question:
Who is doing something that is really different from you?
example from Lifehacker: "I’d love to see _________ answer these same questions."

**Comment by kellobri** [comment]
@stefaniebutland I love all these ideas. I wonder if we could strategize a way to connect people who are interested in interviewing with people who wouldn't mind being interviewed in a way that wouldn't be super forced or uncomfortable. There are probably people who wouldn't mind being interviewed (even twice!) but there are also people who probably would prefer to pass for now. I'd like to see lots of different types of interviewees, like you mentioned, especially people who wouldn't necessarily be immediately forthcoming in a self-nominating situation. But I also don't want anyone to feel pressured into do this because someone else nominated them.

@stefaniebutland If you have some time tomorrow or next week to chat or slack about an organizational strategy, I'd really like that. 

And if anyone has ideas re: the humane sourcing of interviewee candidates, please share!

**Comment by stefaniebutland** [comment]
Last week @kellobri and I talked about how we might facilitate this, given that so many people are interested.

At the unconf, we'll probably put up several pieces of paper on the wall:
1. interviewers - names of people who want to conduct (and write up) an interview
2. interviewees - names of people who are willing to be interviewed, or who an unconf participant would love to interview
3. name-pairs of interviewer(s)-interviewee, with interview time when that's settled.
  - In the case that more than one person is keen to interview the same person, it's important to respect the interviewee's unconf time, so I'd recommend two or more people could talk with one interviewee at the same time.
  - posting a scheduled time there will help in case you want Karthik to take photos, or @nistara to get some video

@kellobri agreed to assemble a draft set of core questions to ask (esp if we are to turn some interviews into a series of rOpenSci blog posts about people's workflows or career paths), plus a list of optional questions to help people get started.

**Comment by kellobri** [comment]
**Summary Post**

Many people seem interested in participating as interviewers, interviewees, or both! @stefaniebutland is going to help us put together some lists and schedules on the first morning. 

**Interviewee Volunteers List** (Hopefully we’ll continue to add)
Karthik Ram
Nicholas Tierney
Noam Ross
Oliver Keyes
Julia Stewart 

**Interview Format**
For the purposes of generating blogs for rOpenSci, I propose that we consider some variation of the following structure: **Basic Stats, Description of a Typical Work Day, Description of Workflow and Thought Process**. I’ve summarized the questions suggested so far in matrix format with the hope that interviewers will traverse the various columns organically and use the questions as a loose guide to direct conversation as necessary. 

**Basic Stats**
Name:
Current preferred job title:
Number of years working in R:
Amount of average work week spent using R:
Additional tools/languages commonly used:

<img width="688" alt="screen shot 2017-05-17 at 7 39 14 pm" src="https://cloud.githubusercontent.com/assets/4359210/26180693/c9a0cc58-3b38-11e7-95d2-25ef14124d6f.png">
<img width="678" alt="screen shot 2017-05-17 at 7 39 29 pm" src="https://cloud.githubusercontent.com/assets/4359210/26180696/ce4f810e-3b38-11e7-8130-729a69f9c208.png">

**Comment by sfirke** [comment]
If I could ask any question of these interviewees, I'd want to know their story: how did you get where you are now?  Both the path they took, and their commentary on it.  I think readers of these interviews would be interested in seeing the variety of routes people have taken, and the advice (implicit or explicit) contained in commentary re: what parts were the most valuable, difficult, etc.

**Comment by stefaniebutland** [comment]
Concrete outcome from this! Thank you @kellobri !

New rOpenSci monthly blog series called ".rprofile". First post is interview with David Smith https://ropensci.org/blog/2017/10/13/rprofile-david-smith/
Look for posts on second Friday of every month
See all here https://ropensci.org/tags/rprofile/
